### ISSUE TITLE
Why the thinning results of each run are different? 

### ISSUE THREAD

**Issue by XiaotianJia** [mwagner9/BEGPUThinning#2]
Thank you very much for your sharing and it helps me a lot. But now I have two problems when I run the code using visual studio: the first one is that the results of each run are different in debug mode; and the second one is the results of nseg and pOut are always 0 in release mode. The following is my code:
const int width = 512;
const int height = 512;
const int depth = 498;
int length = widthheightdepth;
float *out_x = 0;
float *out_y = 0;
float *out_z = 0;
unsigned int out_idx = 0;
unsigned int nsegs = 0;
using PixelType = unsigned char;
PixelType pImage = new PixelType[length];
FILE *fp = fopen("..\mask.raw", "rb");
fread(pImage, sizeof(unsigned char), length, fp);
fclose(fp);
nsegs = CenterlineExtraction(pImage, width, height, depth, 0, 0, &out_x, &out_y, &out_z, &out_idx);
Thinning3D(width, height, depth, pImage, pOut);

Is there some problems with my code？

**Comment by mwagner9** [comment]
The issue should be fixed in version 1.2
